export const MAP_CATEGORY_ORDER = [
  "Ancient Loot",
  "Baitfish",
  "Berry",
  "Chummed Ocean Fish School",
  "Clay",
  "Coconut",
  "Fiber Plant",
  "Flower",
  "Fruit",
  "Huntable Animal",
  "Hexite Meteor",
  "Lake Fish School",
  "Metal Outcrop",
  "Monster Den",
  "Mushroom",
  "Ocean Fish School",
  "Ore Vein",
  "Rare Mushroom",
  "Rare Research",
  "Research",
  "Rock",
  "Rock Boulder",
  "Rock Outcrop",
  "Sailing Cargo",
  "Salt",
  "Sand",
  "Sapling",
  "Seasonal",
  "Seasonal Resource",
  "Stick",
  "Treasure",
  "Tree",
  "Wild Grain",
  "Wild Vegetable",
  "Wonder Resource",
  "Wood Logs",
];

export const MAP_CATEGORY_SET = new Set(MAP_CATEGORY_ORDER);
